services:
  - type: web
    name: bim-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bim-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
    healthCheckPath: /health

  - type: web
    name: bim-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: bim-backend
          property: host
      - key: VITE_FORGE_CLIENT_ID
        sync: false
      - key: VITE_FORGE_CLIENT_SECRET
        sync: false

databases:
  - name: bim-database
    databaseName: bim_db
    user: bim_user
    plan: free